### ISSUE TITLE
Flash message session between frontend and backend is lost

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-app-advanced#183]
### What steps will reproduce the problem?

When I perform an action from backend site and Yii::$app->getSession()->setFlash('success', Yii::t('backend','A test version of this has been sent to administrators.'));

The flash does not appear on page refresh.

I'd like to know how to set a flash message for backend
### What's expected?

Seeing the flash message.
### What do you get instead?

When I return to the frontend site - I happen to see the flash message set earlier. 
### Additional info

Just to check my session cookies. I did this.
a) Logged out of frontend
b) Logged in to back end
c) Performed the action that sets the flash message
d) Returned to frontend expecting maybe a login
e) Because admin had logged in on backend, session was valid on frontend
f) Returning to frontend showed flash message

| Q | A |
| --- | --- |
| Yii vesion |  |
| PHP version |  |
| Operating system |  |

**Comment by samdark** [comment]
It seems you're running both frontend and backend on the same domain. Till recently cookies were not separated so that's why you're logged in automatically in both apps. That's changed in `master` branch. https://github.com/yiisoft/yii2-app-advanced/commit/ec1148c4f62e12098a3eb650f8e66fe6c23a6323 and https://github.com/yiisoft/yii2-app-advanced/commit/bb35a7543aa5b718b01d6cd576d78da9e4193249. Try updating configs and see if it helps.
